### ISSUE TITLE
更新技能树

### ISSUE THREAD

**Issue by unclexiao** [unclexiao/growth#4]
技能树需要修改，现有两种实现方式可供参考：

1. [skillwheel](https://github.com/phodal/skillwheel) by Phodal
2. [skill-map](http://skill-map.stuq.org/) by Stuq

**Comment by xunge0613** [comment]
感觉移动端使用第二种 skill-map 更合适
手机上屏幕小操作第一种可能不方便。（因为那个圈感觉太大了…… 而且要缩放缩小可能有点麻烦？）
第二种相当于第一种可能比较适合小屏的交互方式？

**Comment by phodal** [comment]
两种的实现难度都蛮大的~。StuQ 也是直接拿 D3 做的，233。感觉，都需要实现一个简单的算法。

**Comment by squallySP** [comment]
@phodal 数据在哪里？
我想试试用canvas来实现。

**Comment by phodal** [comment]
@squallySP 上面的两个链接里有~~

**Comment by unclexiao** [comment]
考虑到实现成本较高，以及没有足够的人员投入，经过讨论决定：把**技能树**改为**留言板**：

1. 前端：基于[WeUI](https://weui.io/#panel)实现，主要显示标题、名字、时间；
2. 后台：依赖[LeanCloud](https://leancloud.cn/)平台，目前只做增加与查询；

后续通过Node实现了登录授权，再考虑实现更多功能。

**Comment by unclexiao** [comment]
@GHLgh 提醒下哈，微信小程序是没有DOM节点的，跟传统WEB的canvas会有巨大差别，先模拟器/真机能不能运行，可别高兴太早哈~~

**Comment by xunge0613** [comment]
@unclexiao 小程序自己实现了个 DIY 版本的 canvas，接口和 Web 的比较接近，总体差别不大的哈，这个跟 DOM 无关的。

**Comment by squallySP** [comment]
@unclexiao OK，那就暂时不做技能树咯。
看了一下小程序自己的 canvasAPI，在细节上与H5的canvasAPI还是有些差异的，移植起来可能比较麻烦，而且绘图效果是否一致也不好说。
